# Site settings
title: "zer0Byte.io"
#email: jacob@jacobtomlinson.co.uk
description: "Inspiring Creation."
baseurl: ""
url: "http://0byte.io/"
title_description: "Working with you not for you."
title_image: "http://www.gravatar.com/avatar/e2151d3a7a5234711050f61c8cac1432.jpg?s=512&d=mm"
google_analytics: "UA-00000000-1"
#disqus_account: cartenoire
github_repository: https://github.com/0byte-io/0byte-io.github.io
#addthis_id: ra-a1a1a1a1a1a1a1a1
post_limit: 5

# Social usernames/URLs
twitter_username: Chamunks
github_username:  0byte-io
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/chamunks\">Chamunks</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/0byte-io/0byte-io.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intr a_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
